version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.12.3
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "127.0.0.1:6333:6333"
    volumes:
      - ./storage:/qdrant/storage
      - ./snapshots:/qdrant/snapshots
